### ISSUE TITLE
When using react-router and navigating away from page where widgets are used, there is an uncaught null object error

### ISSUE THREAD

**Issue by cluskii** [andrewsuzuki/react-twitter-widgets#1]
`Uncaught (in promise) TypeError: Cannot read property 'childNodes' of undefined(…)removeChildrenExceptLast @ AbstractWidget.js:75done @ AbstractWidget.js:63(anonymous function) @ Timeline.js:64`

The code it's used in doesn't seem to break, but the console lights up with these (we use a lot of the widgets on a single page). 

If it makes a difference, they are implemented in a [bootstrap modal](http://getbootstrap.com/javascript/#modals)

**Comment by andrewsuzuki** [comment]
Should be fixed in ebb3328 (0.2.4), thanks!
