### ISSUE TITLE
no support for grid type in collections

### ISSUE THREAD

**Issue by thetylerhayes** [andrewsuzuki/react-twitter-widgets#16]
Per https://dev.twitter.com/web/embedded-timelines/oembed there are 2 ways collections can be displayed: list and grid

> Collection timelines only. Set to `grid` to display Tweets in a grid layout

By default it's assumed they're list, but you can pass `widget_type` as `grid` to get a tile-based grid layout

But this code still produces a list not a grid:

```
<Timeline
  dataSource={{
    sourceType: 'collection',
    id: 'some_list_id'
  }}
  options={{
    chrome: 'noheader, nofooter, noborders',
    theme: 'dark',
    widget_type: 'grid',
    height: '400'
  }}
  onLoad={() => console.log('Timeline is loaded!')}
/>
```

**Comment by andrewsuzuki** [comment]
This library uses the widget factory functions, not oEmbed.

See this page for a list of parameters (valid `options` keys): https://dev.twitter.com/web/embedded-timelines/parameters. `widget_type` is not included.

I suspect the documentation on your page is outdated anyways and the `widget_type` parameter just doesn't exist anymore.
