### ISSUE TITLE
Adding option for not showing follow count on follow button

### ISSUE THREAD

**Issue by PSPanesar** [andrewsuzuki/react-twitter-widgets#24]
Hi,

Thanks for a great tool. I wonder if it would be possible to add a prop to the Follow button to set whether the data-show-count option is set or not. That way you could set it to false if you didn't want the follow button to show the number of followers?

Thank you.

**Comment by andrewsuzuki** [comment]
Look at the readme and it'll show you how to supply an `options` prop to a widget.

The parameters available for the Follow button are here: https://dev.twitter.com/web/follow-button/parameters

So, you would have `options={{show_count:false}}`

**Comment by PSPanesar** [comment]
hi Andrew, I added the options prop with  options={{ show_count: false }}  but the Follow button still shows the count? not sure what I've missed. I've read the twitter parameters and it should work. Do you have any advice?

**Comment by andrewsuzuki** [comment]
Ah, as you can see [here](https://dev.twitter.com/web/follow-button/parameters#javascript-example) the options are camel-cased:

`options={{ showCount: false }}`

**Comment by PSPanesar** [comment]
Brilliant! Thanks
