### ISSUE TITLE
support grid template

### ISSUE THREAD

**Issue by gggjtgxing** [andrewsuzuki/react-twitter-widgets#27]
The Twitter for Websites JavaScript library supports dynamic insertion of a collection displayed in a grid template using the twttr.widgets.createGridFromCollection function. Pass a collection ID, target container element, and optional options object to insert an embedded collection displayed in a grid template into your page.

**Comment by andrewsuzuki** [comment]
Twitter has deprecated the grids display type for collections, see here:

https://twittercommunity.com/t/update-on-the-embedded-grid-display-type/119564
