### ISSUE TITLE
Edit CSS styles of Timeline

### ISSUE THREAD

**Issue by heyhujiao** [andrewsuzuki/react-twitter-widgets#29]
How do we edit the CSS style of the Twitter widget? 
Let's say we want to change the background colour of the Timeline...?

**Comment by andrewsuzuki** [comment]
See the readme -- this library is only a proxy for the Twitter Widgets API, so you're limited to their customization options (supplied in the `options` prop).

See here for a table of available options:

https://dev.twitter.com/web/embedded-timelines/parameters
