### ISSUE TITLE
Widget configuration is not found

### ISSUE THREAD

**Issue by Ethaan** [andrewsuzuki/react-twitter-widgets#3]
Im getting.

`Widget configuration is not found.` every time i try to use a `widgetId` different to `600720083413962752`, is there a way to catch errors on the `onLoad` function? 

Looking into the [API reference](https://dev.twitter.com/web/javascript/creating-widgets#create-timeline) it seems like a property `element` exists, maybe we can use it to check if the `timeline` is loaded itself.

**Comment by andrewsuzuki** [comment]
Sorry, I was traveling and just saw this. Should be fixed with #4, bump the version to 1.0.0 and, assuming you're using a Timeline, supply it with the new dataSource object prop (see readme). Thanks.
