### ISSUE TITLE
Uncaught (in promise) Error: No target element specified. Expected: ƒ(tweetId, target, [options]);

### ISSUE THREAD

**Issue by carlosalbertopardo** [andrewsuzuki/react-twitter-widgets#32]
Hello :)

i'm trying to implements a simple tweet element like this in my react app:

```
              <Tweet
                tweetId='1022854752315559937'
                options={{ cards:'hidden', align:'center'  }}
              />
```
It actually shows up correctly on the screen, but in the console i get the error:
Uncaught (in promise) Error: No target element specified. Expected: ƒ(tweetId, target, [options]);

I tried adding the parameter on the Tweet element but i still get the same error in the console.

Am i implementing something wrong?

Thanks!

**Comment by andrewsuzuki** [comment]
Should be fixed in `1.8.0`, let me know if you still have problems.
