### ISSUE TITLE
Mention button "Tweet to"

### ISSUE THREAD

**Issue by amardesi** [andrewsuzuki/react-twitter-widgets#35]
I'd like to allow my users to directly tweet designated user whose material is hosted on my site.
The twitter documentation indicates the ability to direct a tweet to a given user with the addition of a query parameter `screen_name=TwitterDev`
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/mention-button.html

Do you intend to add this feature to the Mention component?

**Comment by andrewsuzuki** [comment]
Hi, sorry for the late reply. You can supply a `username` prop to the Mention button.

```js
<Mention username="TwitterDev" />
```

The documentation you referenced is for the first of two official methods of embedding twitter widgets. This library uses the other method under the hood (in the Twitter documentation it is called the "Javascript factory function" near the bottom of that page.
