### ISSUE TITLE
Warning: componentWillMount has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by Felix83000** [andrewsuzuki/react-twitter-widgets#39]
<img width="1878" alt="Capture d’écran 2019-12-11 à 20 16 02" src="https://user-images.githubusercontent.com/16541780/70652547-10539d80-1c53-11ea-82ee-30818b1890a2.png">

Please move code with side effects to componentDidMount, and set initial state in the constructor of "AbstractWidget" component :)

**Comment by Felix83000** [comment]
This happend when I use the Tweet component.

**Comment by Felix83000** [comment]
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

You may want to follow the official migration.

**Comment by andrewsuzuki** [comment]
Fixed, moved to React Hooks. Released in `1.8.0`.
