### ISSUE TITLE
Updating Timelines for optional WidgetId, various sourceType

### ISSUE THREAD

**Issue by eastbayjake** [andrewsuzuki/react-twitter-widgets#4]
Thanks for your work on this module, @andrewsuzuki! I was trying to use it to create a timeline but as of June 2016 you can no longer create new timeline widgets -- and thus there's no widgetId available although it is required -- but [widgets only need a `screenName` now](https://dev.twitter.com/web/javascript/creating-widgets#create-timeline). There are also several types of timelines and some have different syntax for specifying users.

I was going to make a PR to make `widgetId` optional but this seems like a broad enough change that some prior strategizing might be helpful. What do you think?

**Comment by andrewsuzuki** [comment]
Changed `widgetId` to `dataSource`, now just give it a data source prop (see updated readme). Bumped version to 1.0.0 since this is a breaking change. Thanks!
