### ISSUE TITLE
STYLED SCROLLBAR

### ISSUE THREAD

**Issue by EstopaceMA** [andrewsuzuki/react-twitter-widgets#44]
Can we have also as well the styling of scroll bars

**Comment by andrewsuzuki** [comment]
No. This is just a wrapper around the Twitter library. They don't have an option to style scrollbars.

https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/scripting-factory-functions

You can hide them with the option `chrome: "noscrollbar"`

**Comment by EstopaceMA** [comment]
Thanks for the feedback @andrewsuzuki , it makes sense.
