### ISSUE TITLE
widget is not loading tweets

### ISSUE THREAD

**Issue by BenTokenFinance** [andrewsuzuki/react-twitter-widgets#58]
Error: Twitter could not create widget. If it is a Timeline or Tweet, ensure the screenName/tweetId exists.

**Comment by andrewsuzuki** [comment]
...and does the screenName/tweetId exist?

The Tweet widget is currently working in the demo: https://andrewsuzuki.github.io/react-twitter-widgets/?path=/story/tweet--basic

**Comment by andrewsuzuki** [comment]
Seems to be a Twitter issue. Timelines currently aren't loading on their own website: https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview

**Comment by edcalderon** [comment]
same here any fix?

**Comment by andrewsuzuki** [comment]
@edcalderon I don't think so. Last year a similar event happened with the Timeline component and [someone](https://github.com/andrewsuzuki/react-twitter-widgets/issues/45#issuecomment-889733612) found a working hack, but it doesn't seem to be working for me this time. Either try to contact twitterdev, or dive into Twitter's source code and try to find a similar hack, or wait a day until they fix it

**Comment by BenTokenFinance** [comment]
seems good now
