### ISSUE TITLE
eagerLoadTwitterLibrary import error

### ISSUE THREAD

**Issue by Zenthon** [andrewsuzuki/react-twitter-widgets#63]
Module '"react-twitter-widgets"' has no exported member 'eagerLoadTwitterLibrary'.ts(2305)

Is there a solution to this for react with typescript?

**Comment by wottpal** [comment]
same problem

maybe you can do smfn like

```ts
declare module 'react-twitter-widgets' {
  const eagerLoadTwitterLibrary: any
}
```
