### ISSUE TITLE
Widget suddenly way taller than before?

### ISSUE THREAD

**Issue by AndrewNow** [andrewsuzuki/react-twitter-widgets#65]
Hi all,

I've just come back to a repo that uses this package and noticed that the twitter widget is way taller than before (9000 pixels high?!), when previously I was able to contain it to be about 500 pixels high. 

My code is as follows:

```js
        <Placeholder>
          {sectionInView && (
            <Timeline
              dataSource={{
                sourceType: "profile",
                screenName: "WonderWorksRB",
              }}
              options={{
                height: "530",
                width: "500",
              }}
            />
          )}
        </Placeholder>
```

And my CSS:

```js
const Placeholder = styled.div`
  min-height: 530px;
`
```

Adding a max-height to Placeholder has no effect - in fact when I add a max-height property, the timeline protrudes beyond the wrapper div that contains this widget. I'm having similar issues with the width (it's no longer as responsive as it was) but at least adding a max-width property to the container seems to address the issue somewhat.

There is the `tweetLimit` value which I suppose could override the height of the widget but previously there was a Y-axis overflow scroll which was a much better solution from a UX perspective.

What has changed in the past month or two?

**Comment by andrewsuzuki** [comment]
It's the same for me if I set up a timeline with the vanilla Twitter for Websites library, so it seems to be a problem on their end (this is just a thin wrapper). Despite it being in the documentation, it seems they've deprecated some parameters recently:

https://twittercommunity.com/t/new-timeline-embed-is-not-respecting-documented-parameters/175729

**Comment by AndrewNow** [comment]
Yeah, just saw that post a few moments ago. Unfortunate, I guess I'll just have to set up a workaround with overflow-y: hidden and tack on a 12px border-radius in the meantime lol.

Please keep me posted if ever you notice they revert these changes. Thanks for the great package!

**Comment by hanancs** [comment]
What do you mean by tack on a 12px boarder-radius? I don't get it.

**Comment by AndrewNow** [comment]
> What do you mean by tack on a 12px boarder-radius? I don't get it.

When adding overflow, you also have to add a 12px border radius if you want to replicate the styling of the original widget. Otherwise you end up with squared edges.

**Comment by hanancs** [comment]
Got it. Thanks

**Comment by andrewsuzuki** [comment]
Looks like Twitter has fixed it.
