### ISSUE TITLE
Timeline Widget scroll stopped working after Twitter update

### ISSUE THREAD

**Issue by AoDev** [andrewsuzuki/react-twitter-widgets#66]
Twitter updated their widget recently. Aside from the style change, content scrolling has stopped working for us.
I was wondering if anyone using this package has the same issue.

For example, you can see it here. https://ooki.com/dashboard/lobby

**Comment by unsphere** [comment]
Yes, same issue, and onLoad is also no longer triggered.

**Comment by AoDev** [comment]
Looks like it has been fixed. Scroll is working again in our site.
