### ISSUE TITLE
Can I custom share button text?

### ISSUE THREAD

**Issue by cpx2017** [andrewsuzuki/react-twitter-widgets#68]
Follow from this title. I'm not found parameter to solve this solution. Please suggest me.

In official documentation from twitter I can insert in `a` tag directly like this.

```
<a class="twitter-share-button"
  href="https://twitter.com/intent/tweet"
  data-size="large"
  data-text="custom share text"
  data-url="https://dev.twitter.com/web/tweet-button"
  data-hashtags="example,demo"
  data-via="twitterdev"
  data-related="twitterapi,twitter">
Tweet <-- I can exist my own button text here but this library can't
</a>
```

**Comment by andrewsuzuki** [comment]
Ordinarily yes, there is an example of that here:

https://andrewsuzuki.github.io/react-twitter-widgets/?path=/story/share--default-text

However, Twitter seems to have broken their own widget library recently (see other open issues), so that doesn't seem to be working now.
