### ISSUE TITLE
Twitter Lists do not update with new tweets.

### ISSUE THREAD

**Issue by alphatradingsystems** [andrewsuzuki/react-twitter-widgets#69]
Hello,

I am having an issue where the twitter list will not append any new tweets unless i refresh the component completely.

Is this a limitation of the twitter widget or can i add something to make it update when a new item is in that list?

Thanks

**Comment by andrewsuzuki** [comment]
Looking at Twitter's documentation, I don't see any option to have it update automatically when new tweets are added to the list. So no, it doesn't seem possible.
