### ISSUE TITLE
Check stale time before Twitter request

### ISSUE THREAD

**Issue by beltranrengifo** [andrewsuzuki/react-twitter-widgets#70]
Hi there!
Before anything, thank you for this contribution, makes everything easy and work perfectly fine.

However, I want to comment that there's no way to setup a _stale time_, a period to show just some cached data... I think it can be helpful, as the accounts usually do not update that frequently, for example an user that:
- Navigates to the homepage and the feed is rendered
- the user navigates to a detail page
- the user comes back to the homepage: in this case I think we can spare the new request.

I wonder: is this a topic already discussed here? I did not found it in the issues list.
Do you think it worth the time to give it a try? I can take a look...

And again, thank you!

**Comment by andrewsuzuki** [comment]
That would be a nice feature. But it's hard to imagine a solution that would be compatible with the volatile nature of the remote twitter library. If you'd like to play around with it, you're welcome to.

**Comment by beltranrengifo** [comment]
Okay! Thanks for the answer, I'll close the issue and create another if I make some progress.
