### ISSUE TITLE
<Timeline> component is not working for a known profile.

### ISSUE THREAD

**Issue by laurencefass** [andrewsuzuki/react-twitter-widgets#72]
Im using your component because you have an onload prop which i need to interact with Suspense.

Ive tested alongside  react-twitter-embed widget using same inputs and this widget is not working.

live demo:

https://stackblitz.com/edit/react-ts-x5ckuu

react-twitter-embed does not offer onload prop so i cant use it, so it would be great to get this widget working in the example.

thanks

**Comment by ItzAmirreza** [comment]
This problem still exists
