### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by aendrew** [andrewsuzuki/react-twitter-widgets#9]
I have a use case where I stream tweet IDs into an ElasticSearch database, then use your widgets to render tweets using these IDs. Alas, some of the IDs are from deleted tweets, which silently fail because you call `.then()` and not `.catch()` [here](https://github.com/andrewsuzuki/react-twitter-widgets/blob/master/src/components/Tweet.js#L28). 

I'm admittedly not super familiar with React and am not sure the best way of handling such errors; otherwise I'd submit a PR. :+1:

**Comment by andrewsuzuki** [comment]
The components currently accept an `onLoad` prop, perhaps we can add an `onError` prop as well for custom error handling?

**Comment by aendrew** [comment]
@andrewsuzuki That would be awesome! Does Twitter return errors on invalid tweetId, though? Or have any error handling whatsoever? I've forked your repo and am trying to get it to fail in an intelligent fashion and failing miserably...

**Comment by andrewsuzuki** [comment]
Not sure. In your original post, by "silently fail", did you mean there are no console errors at all when there's an invalid tweet id?

**Comment by aendrew** [comment]
@andrewsuzuki Yes, exactly. Doesn't give a XHR 404 or any sort of promise error, just returns empty markup.

**Comment by andrewsuzuki** [comment]
In that case, Twitter must silence the errors -- if `tw.widgets.createTweet` or any of the other widget creators threw an error it would bubble up since there isn't a `.catch`.

For your use case, it would probably be best to check with the Twitter API for existence first.

**Comment by roma-glushko** [comment]
Hi @andrewsuzuki 👋 any plans to improve this part? Would be super cool to be able to handle tweets which cannot be rendered via tweet widget
